DROP TABLE IF EXISTS Sessions;
DROP TABLE IF EXISTS OAuthTokens;
DROP TABLE IF EXISTS OAuthIssuers;
DROP TABLE IF EXISTS OAuthClients;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS OIDCKeys;
DROP TABLE IF EXISTS KV;